version: '3.0'

services:
  neo4j:
    build:
      context: .
    image: ccatesbt/neo4j-fund-lookup:${IMAGE_TAG:-latest}
    environment:
      # - NEO4J_AUTH=neo4j/test # Just click on the login button without password
      - NEO4J_AUTH=none # Just click on the login button without password
      # - NEO4J_USERNAME=neo4j
      # - NEO4J_PASSWORD=test

    ports:
      - "7474:7474"  # Go to http://localhost:7474/browser/ after bootstrapping
      - "7687:7687"
    volumes:
      - ./import:/var/lib/neo4j/import
      - ./neo4j-runtime/plugins:/plugins"
      - ./cypher_query.cql:/cyphers/uploadReports.cql
